# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'textFields' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for textFields

  target 'textFieldsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'textFieldsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

pod 'IQKeyboardManagerSwift', '6.0.4'

end
