# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'sqlite practice' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for sqlite practice

    pod 'SQLite.swift', '~> 0.12.0'

end
