# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'sqlLite' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for sqlLite

  target 'sqlLiteTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'sqlLiteUITests' do
    # Pods for testing
  end


 pod 'SQLite.swift', '~> 0.12.0'end
