# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SQLiteDB' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SQLiteDB

pod 'SQLite.swift', '~> 0.12.0'
pod 'IQKeyboardManagerSwift', '6.0.4'
pod 'Toast-Swift', '~> 4.0.0'


end
